@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class AnimalLogic LOGIC_COLOR
    Class AnimalStorage STORAGE_COLOR
    Class AnimalModel MODEL_COLOR
    Class Main #grey
    Class Commons LOGIC_COLOR_T2
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI -[#green]> AnimalLogic
UI -right[#green]-> AnimalModel
AnimalLogic -[#blue]-> AnimalStorage
AnimalLogic -down[#blue]-> AnimalModel
Main -[#grey]-> UI
Main -[#grey]-> AnimalLogic
Main -[#grey]-> AnimalStorage
Main -up[#grey]-> AnimalModel
Main -down[hidden]-> Commons

AnimalStorage -up[STORAGE_COLOR].> AnimalModel
AnimalStorage .right[STORAGE_COLOR].>File
User ..> UI
@enduml
