@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package AnimalLogic as LogicPackage {
Class "<<interface>>\nAnimalLogic" as AnimalLogic
Class AnimalLogicManager
}

package AnimalModel as ModelPackage {
Class "<<interface>>\nAnimalModel" as AnimalModel
Class AnimalModelManager
}

package Storage as StoragePackage {
Class "<<interface>>\nStorage" as Storage
Class StorageManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AnimalLogic

AnimalLogicManager .up.|> AnimalLogic
AnimalModelManager .up.|> AnimalModel
StorageManager .up.|> Storage

AnimalLogicManager --> AnimalModel
AnimalLogicManager --> Storage
@enduml
