@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package AnimalLogic as LogicPackage {

Class AnimalCatalogParser
Class XYZCommand
Class CommandResult
Class "{abstract}\nAnimalCommand" as AnimalCommand


Class "<<interface>>\nAnimalLogic" as AnimalLogic
Class AnimalLogicManager
}

package AnimalModel {
Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AnimalLogic

AnimalLogicManager .right.|> AnimalLogic
AnimalLogicManager -right->"1" AnimalCatalogParser
AnimalCatalogParser ..> XYZCommand : creates >

XYZCommand -up-|> AnimalCommand
AnimalLogicManager .left.> AnimalCommand : executes >

AnimalLogicManager --> AnimalModel
AnimalLogicManager --> Storage
Storage --[hidden] AnimalModel
AnimalCommand .[hidden]up.> Storage
AnimalCommand .right.> AnimalModel
note right of XYZCommand: XYZCommand = AddCommand, \nDeleteCommand, etc

AnimalLogic ..> CommandResult
AnimalLogicManager .down.> CommandResult
AnimalCommand .up.> CommandResult : produces >
@enduml
