@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package AnimalModel as AnimalModelPackage <<Rectangle>>{
Class "<<interface>>\nAnimalReadOnlyCatalog" as AnimalReadOnlyCatalog
Class "<<interface>>\nAnimalReadOnlyAnimalUserPrefs" as AnimalReadOnlyAnimalUserPrefs
Class "<<interface>>\nAnimalModel" as AnimalModel
Class AnimalCatalog
Class AnimalModelManager
Class AnimalUserPrefs

Class UniqueAnimalList
Class Animal
Class Name
Class PetId
Class Species
Class Breed
Class Sex
Class DateOfBirth
Class AdmissionDate

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AnimalModel

AnimalCatalog .up.|> AnimalReadOnlyCatalog

AnimalModelManager .up.|> AnimalModel
AnimalModel .right.> AnimalReadOnlyAnimalUserPrefs
AnimalModel .left.> AnimalReadOnlyCatalog
AnimalModelManager -left-> "1" AnimalCatalog
AnimalModelManager -right-> "1" AnimalUserPrefs
AnimalUserPrefs .up.|> AnimalReadOnlyAnimalUserPrefs

AnimalCatalog *--> "1" UniqueAnimalList
UniqueAnimalList --> "~* all" Animal
Animal *--> Name
Animal *--> Breed
Animal *--> Species
Animal *--> PetId
Animal *--> Sex
Animal *--> DateOfBirth
Animal *--> AdmissionDate

Animal -[hidden]up--> I
UniqueAnimalList -[hidden]right-> I

AnimalModelManager --> "~* filtered" Animal
@enduml
