@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

    package "UserPrefs Storage" #F4F6F6{
        Class "<<interface>>\nAnimalUserPrefsStorage" as UserPrefsStorage
        Class JsonAnimalUserPrefsStorage
    }

    Class "<<interface>>\nAnimalStorage" as Storage
    Class AnimalStorageManager

    package "AnimalCatalog Storage" #F4F6F6{
        Class "<<interface>> AnimalCatalogStorage" as AnimalCatalogStorage
        Class JsonAnimalCatalogStorage
        Class JsonSerializableAnimalCatalog
        Class JsonAdaptedAnimal
        Class JsonAdaptedTask
    }
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

AnimalStorageManager .up.|> Storage
AnimalStorageManager -up-> "1" UserPrefsStorage
AnimalStorageManager -up-> "1" AnimalCatalogStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AnimalCatalogStorage

JsonAnimalUserPrefsStorage .up.|> UserPrefsStorage
JsonAnimalCatalogStorage .up.|> AnimalCatalogStorage
JsonAnimalCatalogStorage ..> JsonSerializableAnimalCatalog
JsonSerializableAnimalCatalog --> "*" JsonAdaptedAnimal
JsonAdaptedAnimal --> "*" JsonAdaptedTask

@enduml
