@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AnimalCatalog *-right-> "1" UniqueAnimalList
AnimalCatalog *-right-> "1" UniquePetIdList

UniquePetIdList -[hidden]down- Animal

UniquePetIdList -right-> "*" PetId
UniqueAnimalList -right-> Animal

Animal -up-> "*" PetId

Animal *--> Name
Animal *--> Species
Animal *--> Breed
Animal *--> Sex
Animal *--> DateOfBirth
Animal *--> AdmissionDate
@enduml
