@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":AnimalLogicManager" as AnimalLogicManager LOGIC_COLOR
participant ":AnimalCatalogParser" as AnimalCatalogParser LOGIC_COLOR
participant ":DeleteAnimalCommandParser" as DeleteAnimalCommandParser LOGIC_COLOR
participant "d:DeleteAnimalCommand" as DeleteAnimalCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box AnimalModel MODEL_COLOR_T1
participant ":AnimalModel" as AnimalModel MODEL_COLOR
end box

[-> AnimalLogicManager : execute("delete 1")
activate AnimalLogicManager

AnimalLogicManager -> AnimalCatalogParser : parseCommand("delete 1")
activate AnimalCatalogParser

create DeleteAnimalCommandParser
AnimalCatalogParser -> DeleteAnimalCommandParser
activate DeleteAnimalCommandParser

DeleteAnimalCommandParser --> AnimalCatalogParser
deactivate DeleteAnimalCommandParser

AnimalCatalogParser -> DeleteAnimalCommandParser : parse("1")
activate DeleteAnimalCommandParser

create DeleteAnimalCommand
DeleteAnimalCommandParser -> DeleteAnimalCommand
activate DeleteAnimalCommand

DeleteAnimalCommand --> DeleteAnimalCommandParser : d
deactivate DeleteAnimalCommand

DeleteAnimalCommandParser --> AnimalCatalogParser : d
deactivate DeleteAnimalCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteAnimalCommandParser -[hidden]-> AnimalCatalogParser
destroy DeleteAnimalCommandParser

AnimalCatalogParser --> AnimalLogicManager : d
deactivate AnimalCatalogParser

AnimalLogicManager -> DeleteAnimalCommand : execute()
activate DeleteAnimalCommand

DeleteAnimalCommand -> AnimalModel : deleteAnimal(1)
activate AnimalModel

AnimalModel --> DeleteAnimalCommand
deactivate AnimalModel

create CommandResult
DeleteAnimalCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteAnimalCommand
deactivate CommandResult

DeleteAnimalCommand --> AnimalLogicManager : result
deactivate DeleteAnimalCommand

[<--AnimalLogicManager
deactivate AnimalLogicManager
@enduml
